name: main

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Tidy check
        shell: bash
        run: |
          go mod tidy
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "go.mod and go.sum are dirty, please run `go mod tidy`"
            exit 1
          fi

      - run: go mod verify

      - run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --verbose
          skip-cache: true

      - run: go test -timeout 30s -race github.com/shortcuts/codes/cmd/...

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: test
    steps:
      - uses: actions/checkout@v4

      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}


      - uses: docker/build-push-action@v5.3.0
        with:
          file: Dockerfile
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/shortcuts/codes:latest
            ghcr.io/shortcuts/codes:${{ env.COMMIT_SHA }}
          build-args: |
            version=${{ env.COMMIT_SHA }}
  
