name: main

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  GO_VERSION: '1.22.3'
  KO_DOCKER_REPO: 'ghcr.io/shortcuts/codes'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Tidy check
        shell: bash
        run: |
          go mod tidy
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "go.mod and go.sum are dirty, please run `go mod tidy`"
            exit 1
          fi

      - run: go mod verify

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --verbose
          skip-cache: true

      - run: go test -timeout 30s github.com/shortcuts/codes/cmd/...

  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.TOKEN }}
          release-type: simple

      - name: Setup Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Setup Ko
        if: ${{ steps.release.outputs.release_created }}
        uses: ko-build/setup-ko@v0.6

      - run: make build
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Generate and upload release.yaml
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          tag=$(echo ${{ github.ref }} | cut -c11-)  # get tag name without tags/refs/ prefix.
          ko resolve -t ${tag} > release.yaml
          gh release upload ${tag} release.yaml
